elasticsearch:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: elasticsearch
  environment:
    - COLLECTD_DOCKER_APP=monitoring_elasticsearch
    - LOGSPOUT=ignore
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    - ./data/elasticsearch:/var/lib/elasticsearch
logstash:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: logstash
  links:
    - elasticsearch
  environment:
    - COLLECTD_DOCKER_APP=monitoring_logstash
    - LOGSPOUT=ignore
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    - ./logstash/config:/etc/logstash
    - ./collectd/share:/usr/share/collectd:ro
  command: "logstash -f /etc/logstash/logstash.conf"
kibana:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: kibana:4.3.1
  links:
    - elasticsearch
  environment:
    - COLLECTD_DOCKER_APP=monitoring_kibana
    - LOGSPOUT=ignore
    - VIRTUAL_HOST=kibana.k86.eu
    - VIRTUAL_PROTO=http
    - CERT_NAME=k86.eu
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
influxdb:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: tutum/influxdb
  environment:
    - COLLECTD_DOCKER_APP=monitoring_influxdb
    - LOGSPOUT=ignore
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=bKil27TctOsfXMXfoEhNiydZlixjLcht
    - PRE_CREATE_DB=collectd
    - COLLECTD_DB=collectd
    - COLLECTD_BINDING=:25826
  volumes:
    - ./collectd/share:/usr/share/collectd:ro
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
collectd:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: konjak/collectd
  volumes:
    - ./collectd/collectd.d:/etc/collectd/collectd.d
    - ./collectd/share:/usr/share/collectd
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/ramdisk/docker/monitoring:/ramdisk
    - /mnt/ramdisk/docker/mail:/ramdisk-mail:ro
  links:
    - influxdb
    - logstash
  external_links:
    - nginx:nginx
  environment:
    - COLLECTD_DOCKER_APP=monitoring_collectd
    - LOGSPOUT=ignore
    - HOSTNAME=localhost
    - NETOWRK_HOST=logstash
    - NETWORK_PORT=25826
    - INFLUXDB_HOST=influxdb
    - INFLUXDB_PORT=25826
cgp:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: konjak/cgp
  expose:
    - "80"
  environment:
    - COLLECTD_DOCKER_APP=monitoring_cgp
    - LOGSPOUT=ignore
    - VIRTUAL_HOST=cgp.k86.eu
    - VIRTUAL_PROTO=http
    - CERT_NAME=k86.eu
  volumes:
    - /mnt/ramdisk/docker/monitoring/collectd:/var/lib/collectd
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
grafana:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: konjak/grafana
  links:
    - influxdb
  environment:
    - COLLECTD_DOCKER_APP=monitoring_grafana
    - LOGSPOUT=ignore
    - VIRTUAL_HOST=grafana.k86.eu
    - VIRTUAL_PORT=3000
    - VIRTUAL_PROTO=http
    - CERT_NAME=k86.eu
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=eaSiyM9IDqNGBMRdcD5pH70BXKDJJImS
    - DS_NAME=influxdb
    - DS_TYPE=influxdb
    - DS_ACCESS=proxy
    - DS_URL=http://influxdb:8086
    - DS_PASSWORD=bKil27TctOsfXMXfoEhNiydZlixjLcht
    - DS_USER=root
    - DS_DATABASE=collectd
    - DS_IS_DEFAULT=true
    - API_HOST=localhost
    - API_PORT=3000
    - API_USER=admin
    - API_PASS=eaSiyM9IDqNGBMRdcD5pH70BXKDJJImS
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
logspout:
  cpu_shares: 500
  cpuset: 0,1,2,3
  restart: always
  image: gliderlabs/logspout
  links:
    - logstash
  environment:
    - COLLECTD_DOCKER_APP=monitoring_logspout
    - LOGSPOUT=ignore
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
  command: "syslog://logstash:5555"
